name: Build, Push, and Deploy
on:
  push:
    branches:
      - master
    paths_ignore:
      - '**.md'
      - '.gitignore'

jobs:

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/dannysievers/go-github-actions

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
        
      # Build the Docker image
      - name: Build
        run: |        
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/"$IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/$IMAGE:$GITHUB_SHA
      
      # Push to Dockerhub
      # - name: Build and Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: dannysievers/go-api-example
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     workdir: /home/runner/work/go-github-actions/go/src/github.com/dannysievers/go-github-actions
      #     dockerfile: Dockerfile
      #     snapshot: true
        env:
          GOPATH: /home/runner/work/go-github-actions/go
          GOBIN: /home/runner/work/go-github-actions/go/bin
          IMAGE: go-api-gke
