name: Go CI Workflow
on:
  push:
    branches:
      - master
    paths_ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    paths_ignore:
      - '**.md'
      - '.gitignore'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      # temporary fix for https://github.com/actions/setup-go/issues/12
      - name: Set GOPATH + GOBIN
        run: |
          export GOPATH=$(go env GOPATH)
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          mkdir -p $GOPATH/pkg
          mkdir -p $GOBIN
          mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
          cp -r $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
          ls $GOPATH/src/github.com/$GITHUB_REPOSITORY

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            ls
            dep ensure
          fi

      - name: Run Unit tests
        run: |
          go test ./... -coverprofile cover.out -covermode=atomic
          cat cover.out >> coverage.txt

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt