name: Release
on:
  create:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  GOPATH: /home/runner/work/go-github-actions/go
  GOBIN: /home/runner/work/go-github-actions/go/bin

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: go/src/github.com/dannysievers/go-github-actions

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            export PATH=$PATH:$GOPATH/bin
            mkdir -p $GOBIN
            cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
